# Generated by Django 3.2.19 on 2023-05-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
