# Generated by Django 3.2.19 on 2023-05-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0006_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
